import { getContacts, getConversationMessages, getConversations, updateContactStatus, updateConversationStatus } from "./admin-api.js";

function escapeHtml(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function formatDate(value){if(!value)return "—";const date=new Date(value);return Number.isNaN(date.getTime())?String(value):new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(date);}
function makeItems(conversations,contacts){return [...conversations.map((row)=>({id:row.id,type:"conversation",title:row.user_name||row.user_email||row.user_phone||"Website visitor",subtitle:row.last_intent||"Web conversation",preview:row.latest_message_text||"Open conversation",status:row.status,date:row.last_message_at||row.created_at,raw:row})),...contacts.map((row)=>({id:row.id,type:"contact",title:row.full_name||row.email||"Website contact",subtitle:row.subject||"Contact form",preview:row.message||"",status:row.status,date:row.created_at,raw:row}))].sort((a,b)=>new Date(b.date||0)-new Date(a.date||0));}
function itemHtml(item,index){return `<button class="serenity-inbox-item w-100 text-start border-0" type="button" data-index="${index}"><div class="d-flex justify-content-between gap-2"><strong>${escapeHtml(item.title)}</strong><small>${escapeHtml(formatDate(item.date))}</small></div><div class="small text-muted mt-1">${escapeHtml(item.subtitle)}</div><div class="text-truncate mt-1">${escapeHtml(item.preview)}</div></button>`;}
function messageBody(item,messages=[]){if(!item)return `<div class="serenity-empty">Select a website message or conversation.</div>`;const content=item.type==="conversation"?messages.map((m)=>`<div class="serenity-message"><div class="meta"><strong>${escapeHtml(m.role)}</strong><span>${escapeHtml(formatDate(m.created_at))}</span></div><div>${escapeHtml(m.message_text)}</div></div>`).join(""):`<div class="serenity-message"><div class="meta"><strong>${escapeHtml(item.raw.subject||"Contact form")}</strong><span>${escapeHtml(formatDate(item.date))}</span></div><div>${escapeHtml(item.raw.message||"")}</div></div><div class="mt-3"><strong>Email:</strong> ${escapeHtml(item.raw.email||"—")}</div>`;return `<div class="d-flex justify-content-between align-items-start gap-3 mb-3"><div><h3 class="h5 mb-1">${escapeHtml(item.title)}</h3><div class="text-muted">${escapeHtml(item.subtitle)}</div></div><span class="serenity-status">${escapeHtml(item.status||"new")}</span></div>${content||'<div class="serenity-empty">No message content.</div>'}<div class="d-flex gap-2 mt-3"><button class="btn btn-success btn-sm" id="inbox-close">Close</button>${item.raw.email?`<a class="btn btn-outline-primary btn-sm" href="mailto:${escapeHtml(item.raw.email)}">Reply by email</a>`:""}${item.raw.user_phone||item.raw.phone?`<a class="btn btn-outline-secondary btn-sm" href="tel:${escapeHtml(item.raw.user_phone||item.raw.phone)}">Call</a>`:""}</div>`;}

let items=[];let selected=0;
async function openItem(index){selected=index;document.querySelectorAll(".serenity-inbox-item").forEach((el,i)=>el.classList.toggle("active",i===index));const item=items[index];let messages=[];if(item?.type==="conversation"){const data=await getConversationMessages(item.id);messages=data.messages||[];}document.getElementById("serenity-inbox-message").innerHTML=messageBody(item,messages);document.getElementById("inbox-close")?.addEventListener("click",async()=>{if(item.type==="conversation")await updateConversationStatus(item.id,"closed");else await updateContactStatus(item.id,"closed");await load();});}
async function load(){const target=document.getElementById("serenity-page-root");const [conversationData,contactData]=await Promise.all([getConversations(),getContacts()]);items=makeItems(conversationData.conversations||[],contactData.contactMessages||[]);target.innerHTML=`<div class="serenity-page"><div class="serenity-page-header"><div><h2>Website Inbox</h2><p>Website conversations and contact-form messages from Serenity public channels.</p></div><div class="serenity-actions"><a class="btn btn-outline-primary" href="/operations?resource=callbacks">Callbacks</a><a class="btn btn-outline-primary" href="/operations?resource=website-leads">Leads</a></div></div><div class="serenity-inbox-layout"><div class="serenity-card serenity-inbox-list">${items.length?items.map(itemHtml).join(""):'<div class="serenity-empty">No website messages.</div>'}</div><div class="serenity-card serenity-panel" id="serenity-inbox-message"></div></div></div>`;document.querySelectorAll(".serenity-inbox-item").forEach((el)=>el.addEventListener("click",()=>openItem(Number(el.dataset.index||0))));await openItem(items.length?Math.min(selected,items.length-1):0);}
export async function initPage(){try{await load();}catch(error){document.getElementById("serenity-page-root").innerHTML=`<div class="alert alert-danger serenity-error">${escapeHtml(error.message)}</div>`;}}
